# Generated by Django 4.2.2 on 2023-06-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='des',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
